name: kanemaonline
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  blurrycontainer: ^1.0.2
  palette_generator: ^0.3.3+3
  appinio_video_player: ^1.3.0
  flutter_bounceable: ^1.1.0
  animate_do: ^3.3.4
  cached_video_player: ^2.0.4
  chewie: ^1.5.0
  video_player: ^2.6.0
  multi_value_listenable_builder: ^0.0.2
  volume_controller: ^2.0.7
  syncfusion_flutter_sliders: ^25.1.41
  syncfusion_flutter_core: ^25.1.41
  screen_brightness: ^1.0.1
  statusbarz: ^1.0.14
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  package_rename: ^1.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#121212"
  image: assets/images/logo-white.png
  color_dark: "#121212"
  image_dark: assets/images/logo-white.png

  android_12:
    image: assets/images/logo-white.png
    icon_background_color: "#121212"
    image_dark: assets/images/logo-white.png
    icon_background_color_dark: "#121212"

package_rename_config:
  android:
    app_name: "Kanema Online"
    package_name: com.kanemaonline.app 
    override_old_package: com.kanemaonline.kanemaonline 
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "Kanema Online"
    bundle_name: kanemaonline # (String) The bundle name of the ios app
    package_name: kanemaonline # (String) The product bundle identifier of the ios app


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/videos/


  
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 300
        

  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
